### ISSUE TITLE
终端执行命令“python3 main.py https://live.douyin.com/566064676588”后报错

### ISSUE THREAD

**Issue by 812602984** [gll19920817/douyin_web_live#1]
终端执行命令“python3 main.py https://live.douyin.com/566064676588”后报错如下:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mg/douyin_web_live/scripts/webdriver.py", line 28, in go
    with webdriver.Chrome(options=chrome_options,
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by gll19920817** [comment]
报错：本地缺少chromedirver

解决方法(两种方法)：
1、查看本机chrome版本号，下载对应的chromedriver see: [https://chromedriver.chromium.org/downloads](https://chromedriver.chromium.org/downloads)

2、brew安装chromedriver see: [https://formulae.brew.sh/cask/chromedriver](https://formulae.brew.sh/cask/chromedriver)
