### ISSUE TITLE
这个报错怎么解决

### ISSUE THREAD

**Issue by crytjy** [gll19920817/douyin_web_live#23]
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    w.run()
  File "/www/wwwroot/python/douyin_web_live/scripts/watcher.py", line 21, in run
    self.observer.start()
  File "/usr/local/lib/python3.7/dist-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/local/lib/python3.7/dist-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/local/lib/python3.7/dist-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/local/lib/python3.7/dist-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/local/lib/python3.7/dist-packages/watchdog/observers/inotify_c.py", line 169, in __init__
    self._add_watch(path, event_mask)
  File "/usr/local/lib/python3.7/dist-packages/watchdog/observers/inotify_c.py", line 384, in _add_watch
    Inotify._raise_error()
  File "/usr/local/lib/python3.7/dist-packages/watchdog/observers/inotify_c.py", line 404, in _raise_error
    raise OSError(err, os.strerror(err))
FileNotFoundError: [Errno 2] No such file or directory
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/www/wwwroot/python/douyin_web_live/scripts/webdriver.py", line 35, in go
    executable_path=config()['webdriver']['bin']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chromium/webdriver.py", line 98, in __init__
    options=options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x56158ee6a7d3 <unknown>
#1 0x56158ebc6688 <unknown>
#2 0x56158ebe7a38 <unknown>
#3 0x56158ebe568f <unknown>
#4 0x56158ec20355 <unknown>
#5 0x56158ec1a5a3 <unknown>
#6 0x56158ebefddc <unknown>
#7 0x56158ebf0de5 <unknown>
#8 0x56158ee9b49d <unknown>
#9 0x56158eeb460c <unknown>
#10 0x56158ee9d205 <unknown>
#11 0x56158eeb4ee5 <unknown>
#12 0x56158ee91070 <unknown>
#13 0x56158eed0488 <unknown>

**Comment by FedoraLinux1** [comment]
安装所有包了么？

pip install -r requirements.txt -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com

**Comment by crytjy** [comment]
都装了。网上查了selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary，说是版本对不上，但不知道该装哪个版本

**Comment by FedoraLinux1** [comment]
> 都装了。网上查了selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary，说是版本对不上，但不知道该装哪个版本

试试看弄一个虚拟的Python环境，然后重新安装[requirements.txt]里版本的包

**Comment by crytjy** [comment]
试了几次还是一样的报错，你python用哪个版本的？

**Comment by crytjy** [comment]
![1653983530(1)](https://user-images.githubusercontent.com/38123501/171121539-beb8a80c-4c32-4549-903d-63b934aadcaf.png)

现在这这个错误

**Comment by FedoraLinux1** [comment]
Python 3.8.13

**Comment by crytjy** [comment]
![1653986532(1)](https://user-images.githubusercontent.com/38123501/171131549-b15d7f3a-7de0-4b4c-87e1-80c3b1ce4d67.png)
跑起来了。但怎么是这样的

**Comment by FedoraLinux1** [comment]
先运行{ mitmproxy },然后再运行{ main.py ]

**Comment by FedoraLinux1** [comment]
> 是这样操作的，运行mitmproxy 后就是这图的数据请求，运行main.py，没有任何输出

想来还是你没有弄对,q:7625926

**Comment by gll19920817** [comment]
> ![1653983530(1)](https://user-images.githubusercontent.com/38123501/171121539-beb8a80c-4c32-4549-903d-63b934aadcaf.png)
> 
> 现在这这个错误

第一个报错信息是watchdog监控的目录不存在，在config/settings.yml 修改watchdog.dir 值为你本机的目录绝对路径
第二个报错信息是你机器没装mongodb吧

**Comment by gll19920817** [comment]
> 都装了。网上查了selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary，说是版本对不上，但不知道该装哪个版本

地址栏输入 chrome://settings/help 查看chrome版本号

**Comment by crytjy** [comment]
windows环境的跑起来了。linux的还没有，我再研究下，谢谢各位大神
