### ISSUE TITLE
小白问下（Chrome浏览器请配置于webdriver.chrome.bin）这里地址格式怎么写啊 一直不成功

### ISSUE THREAD

**Issue by yanyuandi** [gll19920817/douyin_web_live#40]
chrome:
    bin: chromedriver
就这里，格式是什么，怎么试也没成功

**Comment by FedoraLinux1** [comment]
下载 Windows版本，32位 64位都行，然后放在代码主目录下，再运行

**Comment by yanyuandi** [comment]
> 下载 Windows版本，32位 64位都行，然后放在代码主目录下，再运行

这个我知道  我看说明这里不是得填Chromedriver的地址 我不知道地址用什么格式  双引号什么的我都试了 运行main.py一直是这里报错

**Comment by FedoraLinux1** [comment]
> webdriver:
>   headless: False
>   use: chrome
>   edge:
>     bin: msedgedriver.exe
>   chrome:
>     bin: chromedriver.exe
>     no_sandbox: True
比如上面，use：是使用下面edge还是chrome，我这里填的是chrome

**Comment by yanyuandi** [comment]
> 下载 Windows版本，32位 64位都行，然后放在代码主目录下，再运行

webdriver:
  headless: False
  use: chrome
  edge:
    bin: msedgedriver.exe
  chrome:
    bin: C:/Users/Administrator/Desktop/douyin_web_live-main/config/chromedriver.exe
    no_sandbox: True

啊？不是这样给个详细的路径吗 直接bin: chromedriver.exe就行吗

**Comment by yanyuandi** [comment]
> > webdriver:
> > headless: False
> > use: chrome
> > edge:
> > bin: msedgedriver.exe
> > chrome:
> > bin: chromedriver.exe
> > no_sandbox: True
> > 比如上面，use：是使用下面edge还是chrome，我这里填的是chrome

这样运行main.py直接报错

C:\Users\Administrator\Desktop\douyin_web_live-main>main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\douyin_web_live-main\main.py", line 11, in <module>
    browser_manager = init_browser_manager()
  File "C:\Users\Administrator\Desktop\douyin_web_live-main\browser\manager.py", line 94, in init_manager
    _manager = BrowserManager()
  File "C:\Users\Administrator\Desktop\douyin_web_live-main\browser\manager.py", line 26, in __init__
    self._driver: IDriver = self._mapping[_config]()
  File "C:\Users\Administrator\Desktop\douyin_web_live-main\browser\chrome.py", line 31, in __init__
    self.browser = webdriver.Chrome(options=options,
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
Backtrace:

**Comment by yanyuandi** [comment]
> 

换成edge可以了 十分感谢

**Comment by WangShuXian6** [comment]
> 下载 Windows版本，32位 64位都行，然后放在代码主目录下，再运行

感谢，试了一晚上，原来是放代码根目录，我说怎么一直提示文件不存在~~~~~
